version: "3.9"

services:
  db:
    volumes:
      - pg_data:/var/lib/postgresql/data
    image: postgres
    env_file:
      - ./.env.dev
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
  
  redis:
    image: redis:latest
    container_name: redis

  celery:
    build:
      context: .
    command: >
      celery -A app worker -l info -Q pokemon_task_queue 
      --pool=prefork --concurrency=1 --uid=nobody --gid=nogroup
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A app beat -l info
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

volumes:
  pg_data:
