# Generated by Django 3.2.16 on 2022-10-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "abilities",
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("height", models.IntegerField(null=True)),
                ("weight", models.IntegerField(null=True)),
                ("stats", models.JSONField(null=True)),
                ("sprite", models.URLField(null=True)),
                (
                    "abilities",
                    models.ManyToManyField(
                        related_name="pokemon", to="pokemon.Ability"
                    ),
                ),
            ],
        ),
    ]
